mutation CreateUser($email: String!, $passwordHash: String!) @auth(level: PUBLIC, insecureReason: "Email and password validated on the client") {
  user_insert(data: {email: $email, passwordHash: $passwordHash, createdAt_expr: "request.time", id_expr: "uuidV4()"})
}

query GetUserByEmail($email: String!) @auth(level: PUBLIC, insecureReason: "Email is non-sensitive and used for login purposes") {
  users(where: {email: {eq: $email}}) {
    id
    email
    passwordHash
  }
}

mutation CreateSession($userId: UUID!, $sessionToken: String!, $userAgent: String, $ipAddress: String, $expiresAt: Timestamp!) @auth(level: USER) {
  session_insert(data: {userId: $userId, sessionToken: $sessionToken, userAgent: $userAgent, ipAddress: $ipAddress, expiresAt: $expiresAt, createdAt_expr: "request.time", id_expr: "uuidV4()"})
}

mutation DeleteSession($id: UUID!) @auth(level: USER) {
  session_delete(key: {id: $id})
}